"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.router = void 0;
const express_1 = require("express");
const auth_1 = require("../controllers/agent/auth");
const agent_1 = require("../controllers/agent/agent");
const validate_agent_1 = require("../controllers/agent/validate-agent");
exports.router = express_1.Router();
exports.router.post('/agent', auth_1.createAgent);
exports.router.post('/agent/login', auth_1.loginAgentWithPhoneAndPassword);
exports.router.get('/agent/logout', validate_agent_1.validateAgent, auth_1.logoutAgent);
exports.router.get('/agent', validate_agent_1.getAgent);
exports.router.post('/agent/add-service/:id/:serviceId', agent_1.AddService);
exports.router.delete('/agent/add-service/:id/:serviceId', agent_1.removeServices);
exports.router.patch('/agent/bankinfo/:id', agent_1.updateBankInfo);
exports.router.patch('/agent/businessinfo/:id', agent_1.updateBusinessInfo);
