"use strict";
exports.__esModule = true;
exports.router = void 0;
var express_1 = require("express");
var auth_1 = require("../controllers/agent/auth");
var agent_1 = require("../controllers/agent/agent");
var validate_agent_1 = require("../controllers/agent/validate-agent");
exports.router = express_1.Router();
exports.router.post('/agent', auth_1.createAgent);
exports.router.post('/agent/login', auth_1.loginAgentWithPhoneAndPassword);
exports.router.get('/agent/logout', validate_agent_1.validateAgent, auth_1.logoutAgent);
exports.router.get('/agent', validate_agent_1.getAgent);
exports.router.post('/agent/add-service/:id/:serviceId', agent_1.AddService);
exports.router["delete"]('/agent/add-service/:id/:serviceId', agent_1.removeServices);
exports.router.patch('/agent/bankinfo/:id', agent_1.updateBankInfo);
exports.router.patch('/agent/businessinfo/:id', agent_1.updateBusinessInfo);
exports.router.patch('/agent/resetpassword/:id', agent_1.resetPassword);
exports.router.patch('/agent/changestatus/:id/:status', agent_1.changeAccountStatus);
