"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = require("express");
const service_1 = require("../controllers/service/service");
const router = express_1.Router();
router.post('/service', service_1.createService);
router.get('/services', service_1.getServices);
router.get('/service/:id', service_1.getService);
router.patch('/service/:_id', service_1.editService);
router.delete('/service/:id', service_1.deleteService);
exports.default = router;
